stages:
  - deploy

deploy_dev:
  stage: deploy
  image: node:20
  # Ce job ne s'exécute QUE si la modification se fait sur la branche "develop"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  script:
    - echo "Déploiement automatique sur AWS (Dev) en cours..."
    - export NEXT_PUBLIC_COMMIT_SHA=$CI_COMMIT_SHORT_SHA
    - npm ci
    - npx prisma generate
    - npx sst deploy --stage dev
  environment:
    name: dev
    url: https://dev.cidrerie-vulcain.ch

deploy_sandbox:
  stage: deploy
  image: node:20
  # Ce job ne s'exécute QUE si la modification se fait sur la branche "sandbox"
  rules:
    - if: '$CI_COMMIT_BRANCH == "sandbox"'
  script:
    - echo "Déploiement automatique sur AWS (Sandbox) en cours..."
    - export NEXT_PUBLIC_COMMIT_SHA=$CI_COMMIT_SHORT_SHA
    - npm ci
    - npx prisma generate
    - npx sst deploy --stage sandbox
  environment:
    name: sandbox
    url: https://sandbox.cidrerie-vulcain.ch
