import { Product } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Cidre Doux 2026',
    category: 'Cidre',
    year: 2026,
    price: 9.0,
    stock: 20,
    description: 'Un cidre doux avec des arômes fruités et sucrés',
    image: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=400',
    active: true,
  },
  {
    id: '2',
    name: 'Cidre Brut 2024',
    category: 'Cidre',
    year: 2024,
    price: 9.0,
    stock: 35,
    description: 'Cidre brut aux notes acidulées et rafraîchissantes',
    image: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=400',
    active: true,
  },
  {
    id: '3',
    name: 'Cidre Rosé 2025',
    category: 'Cidre',
    year: 2025,
    price: 10.0,
    stock: 42,
    description: 'Cidre rosé élégant avec des arômes floraux délicats',
    image: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=400',
    active: true,
  },
  {
    id: '4',
    name: "Eau-de-vie de pomme",
    category: 'Eau-de-vie',
    price: 35.0,
    stock: 30,
    description: 'Eau-de-vie artisanale distillée avec soin',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400',
    active: true,
  },
  {
    id: '5',
    name: 'Liqueur de pomme',
    category: 'Liqueur',
    price: 25.0,
    stock: 18,
    description: 'Liqueur douce et parfumée aux pommes du verger',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400',
    active: true,
  },
  {
    id: '6',
    name: 'Cidre de cuisine',
    category: 'Cuisine',
    price: 6.0,
    stock: 0,
    description: 'Cidre idéal pour la cuisine, vinaigre de cidre artisanal',
    image: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=400',
    active: false,
  },
]

export const CATEGORIES = [
  { id: 'Cidre', label: 'Cidres' },
  { id: 'Eau-de-vie', label: 'Eaux de vie / Liqueurs / Cidre de cuisine' },
] as const
